import math

AMPLITUDE = math.pi / 4
FREQUENCY = 20
PHASEOFFSET = 0



AMPLITUDE_FRONT_LEG = math.pi / 4
FREQUENCY_FRONT_LEG = 20
PHASEOFFSET_FRONT_LEG = 0
MOTOR_MAX_FORCE_FRONT_LEG = 35

AMPLITUDE_BACK_LEG= math.pi / 4
FREQUENCY_BACK_LEG = 50
PHASEOFFSET_BACK_LEG = 1
MOTOR_MAX_FORCE_BACK_LEG = 35

NUM_ITERATIONS = 1000 